In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\User\Desktop\Health Risk Predictor\synthetic_health_data.csv")

In [3]:
df

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium
...,...,...,...,...,...,...,...,...,...,...
3995,35,Poor,7,7,Low,16.6,No,Low,Yes,Low
3996,22,Average,6,8,Medium,38.8,No,Low,Yes,Low
3997,20,Poor,5,8,Low,30.3,No,Medium,Yes,Medium
3998,40,Poor,2,3,Low,35.0,No,Low,Yes,Medium
3999,43,Average,7,11,Medium,25.2,Yes,Medium,Yes,Low

In [4]:
df.shape

(4000, 10)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   object
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   object
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object
 7   alcohol         4000 non-null   object
 8   family_history  4000 non-null   object
 9   risk_level      4000 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB

In [6]:
df.isna().sum()

age               0
diet              0
exercise_days     0
sleep_hours       0
stress            0
bmi               0
smoking           0
alcohol           0
family_history    0
risk_level        0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium

In [9]:
df['age'].max()

80

In [10]:
df['diet'].value_counts()

diet
Average    1987
Poor       1216
Good        797
Name: count, dtype: int64

In [11]:
df['exercise_days'].max()

7

In [12]:
df['exercise_days'].min()

0

In [13]:
df['sleep_hours'].max()

12

In [14]:
df['sleep_hours'].min()

3

In [15]:
categorical_col=['diet','stress','smoking','alcohol','family_history','risk_level']

In [16]:
from sklearn.preprocessing import LabelEncoder

In [17]:
encoders={}

In [18]:
for i in categorical_col:
    le=LabelEncoder()
    df[i]=le.fit_transform(df[i])
    encoders[i]=le

In [19]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [20]:
from sklearn.model_selection import train_test_split

In [21]:
x=df.drop(columns='risk_level')
y=df['risk_level']

In [22]:
print(x.columns)

Index(['age', 'diet', 'exercise_days', 'sleep_hours', 'stress', 'bmi',
       'smoking', 'alcohol', 'family_history'],
      dtype='object')

In [23]:
print(y.name)

risk_level

In [24]:
x_train, x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [25]:
#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [26]:
#model=LogisticRegression()
model=RandomForestClassifier(n_estimators=100,random_state=42)

In [27]:
model.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [28]:
print(x_train.dtypes)        
print(x_train.info())       
print(y_train.unique())

age                 int64
diet                int32
exercise_days       int64
sleep_hours         int64
stress              int32
bmi               float64
smoking             int32
alcohol             int32
family_history      int32
dtype: object
<class 'pandas.core.frame.DataFrame'>
Index: 3200 entries, 3994 to 3174
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             3200 non-null   int64
 1   diet            3200 non-null   int32
 2   exercise_days   3200 non-null   int64
 3   sleep_hours     3200 non-null   int64
 4   stress          3200 non-null   int32
 5   bmi             3200 non-null   float64
 6   smoking         3200 non-null   int32
 7   alcohol         3200 non-null   int32
 8   family_history  3200 non-null   int32
dtypes: float64(1), int32(5), int64(3)
memory usage: 187.5 KB
None
[2 1 0]

In [29]:
from sklearn.metrics import accuracy_score

In [30]:
y_pred=model.predict(x_test)

In [31]:
from sklearn.metrics import accuracy_score

In [32]:
y_pred=model.predict(x_test)

In [33]:
acc=accuracy_score(y_pred,y_test)

In [34]:
print("accuracy_score of you model",acc)

accuracy_score of you model 0.96375

In [35]:
#demo

In [36]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [37]:
model.predict([[56,2,3,4,0,19.9,0,0,1]])

C:\Users\User\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])

In [38]:
import pickle

In [39]:
pickle.dump(model,open("Health_risk_predict.pkl","wb"))

In [40]:
with open("label_encoders.pkl","wb") as f:
    pickle.dump(encoders,f)

In [41]:
pip install streamlit

Defaulting to user installation because normal site-packages is not writeable
Collecting streamlit
  Downloading streamlit-1.57.0-py3-none-any.whl.metadata (9.6 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.1.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Downloading blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.1.1-py3-none-any.whl.metadata (5.8 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.3.3-py3-none-any.whl.metadata (2.6 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.49-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\user\appdata\roaming\python\python311\site-packages (from streamlit) (1.26.2)
Requirement already satisfied: packaging>=20 in c:\users\user\appdata\roaming\python\python311\site-packages (from streamlit) (23.2)
Requirement already satisfied: pandas<4,>=1.4.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from streamlit) (2.1.4)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from streamlit) (10.1.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting protobuf<8,>=3.20 (from streamlit)
  Downloading protobuf-7.34.1-cp310-abi3-win_amd64.whl.metadata (595 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-24.0.0-cp311-cp311-win_amd64.whl.metadata (3.0 kB)
Collecting requests<3,>=2.27 (from streamlit)
  Downloading requests-2.33.1-py3-none-any.whl.metadata (4.8 kB)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from streamlit) (4.13.2)
Collecting starlette>=0.40.0 (from streamlit)
  Downloading starlette-1.0.0-py3-none-any.whl.metadata (6.3 kB)
Collecting uvicorn>=0.30.0 (from streamlit)
  Downloading uvicorn-0.46.0-py3-none-any.whl.metadata (6.7 kB)
Collecting httptools>=0.6.3 (from streamlit)
  Downloading httptools-0.7.1-cp311-cp311-win_amd64.whl.metadata (3.6 kB)
Collecting anyio>=4.0.0 (from streamlit)
  Downloading anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Collecting python-multipart>=0.0.10 (from streamlit)
  Downloading python_multipart-0.0.27-py3-none-any.whl.metadata (2.1 kB)
Collecting websockets>=12.0.0 (from streamlit)
  Downloading websockets-16.0-cp311-cp311-win_amd64.whl.metadata (7.0 kB)
Collecting itsdangerous>=2.1.2 (from streamlit)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
     ---------------------------------------- 0.0/44.3 kB ? eta -:--:--
     --------------------------- ------------ 30.7/44.3 kB 1.4 MB/s eta 0:00:01
     ----------------------------------- -- 41.0/44.3 kB 393.8 kB/s eta 0:00:01
     -------------------------------------- 44.3/44.3 kB 366.1 kB/s eta 0:00:00
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting narwhals>=2.4.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading narwhals-2.20.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: idna>=2.8 in c:\users\user\appdata\roaming\python\python311\site-packages (from anyio>=4.0.0->streamlit) (3.10)
Requirement already satisfied: colorama in c:\users\user\appdata\roaming\python\python311\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from pandas<4,>=1.4.0->streamlit) (2023.4)
Collecting charset_normalizer<4,>=2 (from requests<3,>=2.27->streamlit)
  Downloading charset_normalizer-3.4.7-cp311-cp311-win_amd64.whl.metadata (41 kB)
     ---------------------------------------- 0.0/41.7 kB ? eta -:--:--
     --------- ------------------------------ 10.2/41.7 kB ? eta -:--:--
     -------------------------------------  41.0/41.7 kB 487.6 kB/s eta 0:00:01
     -------------------------------------- 41.7/41.7 kB 335.1 kB/s eta 0:00:00
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\user\appdata\roaming\python\python311\site-packages (from requests<3,>=2.27->streamlit) (2.4.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\user\appdata\roaming\python\python311\site-packages (from requests<3,>=2.27->streamlit) (2025.6.15)
Requirement already satisfied: h11>=0.8 in c:\users\user\appdata\roaming\python\python311\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading markupsafe-3.0.3-cp311-cp311-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: attrs>=22.2.0 in c:\users\user\appdata\roaming\python\python311\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.3.0)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp311-cp311-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas<4,>=1.4.0->streamlit) (1.16.0)
Downloading streamlit-1.57.0-py3-none-any.whl (9.2 MB)
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.2 MB 1.9 MB/s eta 0:00:05
   ---------------------------------------- 0.1/9.2 MB 975.2 kB/s eta 0:00:10
    --------------------------------------- 0.1/9.2 MB 1.0 MB/s eta 0:00:14
    --------------------------------------- 0.2/9.2 MB 687.0 kB/s eta 0:00:14
   - -------------------------------------- 0.2/9.2 MB 686.8 kB/s eta 0:00:14
   - -------------------------------------- 0.2/9.2 MB 686.8 kB/s eta 0:00:14
   - -------------------------------------- 0.3/9.2 MB 561.1 kB/s eta 0:00:16
   - -------------------------------------- 0.3/9.2 MB 571.2 kB/s eta 0:00:16
   - -------------------------------------- 0.4/9.2 MB 636.5 kB/s eta 0:00:14
   - -------------------------------------- 0.4/9.2 MB 636.6 kB/s eta 0:00:14
   - -------------------------------------- 0.4/9.2 MB 624.8 kB/s eta 0:00:15
   -- ------------------------------------- 0.5/9.2 MB 683.6 kB/s eta 0:00:13
   -- ------------------------------------- 0.6/9.2 MB 735.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.6/9.2 MB 755.7 kB/s eta 0:00:12
   --- ------------------------------------ 0.7/9.2 MB 798.7 kB/s eta 0:00:11
   --- ------------------------------------ 0.8/9.2 MB 851.5 kB/s eta 0:00:10
   --- ------------------------------------ 0.9/9.2 MB 863.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.9/9.2 MB 864.1 kB/s eta 0:00:10
   ---- ----------------------------------- 0.9/9.2 MB 876.6 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/9.2 MB 849.5 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/9.2 MB 838.8 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/9.2 MB 834.2 kB/s eta 0:00:10
   ---- ----------------------------------- 1.0/9.2 MB 834.2 kB/s eta 0:00:10
   ---- ----------------------------------- 1.1/9.2 MB 776.1 kB/s eta 0:00:11
   ---- ----------------------------------- 1.1/9.2 MB 776.1 kB/s eta 0:00:11
   ---- ----------------------------------- 1.1/9.2 MB 716.0 kB/s eta 0:00:12
   ---- ----------------------------------- 1.1/9.2 MB 729.0 kB/s eta 0:00:12
   ----- ---------------------------------- 1.2/9.2 MB 719.5 kB/s eta 0:00:12
   ----- ---------------------------------- 1.2/9.2 MB 742.6 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 740.1 kB/s eta 0:00:11
   ----- ---------------------------------- 1.3/9.2 MB 620.1 kB/s eta 0:00:13
   ----- ---------------------------------- 1.3/9.2 MB 620.1 kB/s eta 0:00:13
   ----- ---------------------------------- 1.3/9.2 MB 602.4 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.2 MB 602.4 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.2 MB 602.4 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.2 MB 578.0 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.2 MB 578.0 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.2 MB 559.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.3/9.2 MB 559.2 kB/s eta 0:00:15
   ----- ---------------------------------- 1.3/9.2 MB 553.3 kB/s eta 0:00:15
   ----- ---------------------------------- 1.4/9.2 MB 543.3 kB/s eta 0:00:15
   ----- ---------------------------------- 1.4/9.2 MB 534.7 kB/s eta 0:00:15
   ----- ---------------------------------- 1.4/9.2 MB 534.7 kB/s eta 0:00:15
   ------ --------------------------------- 1.4/9.2 MB 529.9 kB/s eta 0:00:15
   ------ --------------------------------- 1.4/9.2 MB 529.9 kB/s eta 0:00:15
   ------ --------------------------------- 1.4/9.2 MB 529.9 kB/s eta 0:00:15
   ------ --------------------------------- 1.4/9.2 MB 529.9 kB/s eta 0:00:15
   ------ --------------------------------- 1.4/9.2 MB 495.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.4/9.2 MB 495.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.4/9.2 MB 495.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.4/9.2 MB 495.1 kB/s eta 0:00:16
   ------ --------------------------------- 1.4/9.2 MB 466.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.4/9.2 MB 466.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.4/9.2 MB 466.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.4/9.2 MB 466.2 kB/s eta 0:00:17
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.4/9.2 MB 438.0 kB/s eta 0:00:18
   ------ --------------------------------- 1.5/9.2 MB 412.5 kB/s eta 0:00:19
   ------ --------------------------------- 1.5/9.2 MB 412.5 kB/s eta 0:00:19
   ------ --------------------------------- 1.5/9.2 MB 412.5 kB/s eta 0:00:19
   ------ --------------------------------- 1.5/9.2 MB 402.2 kB/s eta 0:00:20
   ------ --------------------------------- 1.5/9.2 MB 402.2 kB/s eta 0:00:20
   ------ --------------------------------- 1.5/9.2 MB 391.5 kB/s eta 0:00:20
   ------ --------------------------------- 1.5/9.2 MB 391.5 kB/s eta 0:00:20
   ------ --------------------------------- 1.5/9.2 MB 391.5 kB/s eta 0:00:20
   ------ --------------------------------- 1.5/9.2 MB 376.7 kB/s eta 0:00:21
   ------ --------------------------------- 1.5/9.2 MB 373.4 kB/s eta 0:00:21
   ------ --------------------------------- 1.5/9.2 MB 373.4 kB/s eta 0:00:21
   ------ --------------------------------- 1.5/9.2 MB 369.9 kB/s eta 0:00:21
   ------ --------------------------------- 1.5/9.2 MB 369.9 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 366.5 kB/s eta 0:00:21
   ------ --------------------------------- 1.6/9.2 MB 343.5 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.2 MB 343.5 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.2 MB 340.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.2 MB 340.9 kB/s eta 0:00:23
   ------ --------------------------------- 1.6/9.2 MB 340.9 kB/s eta 0:00:23
   ------- -------------------------------- 1.7/9.2 MB 344.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.7/9.2 MB 347.8 kB/s eta 0:00:22
   ------- -------------------------------- 1.7/9.2 MB 354.0 kB/s eta 0:00:22
   ------- -------------------------------- 1.8/9.2 MB 355.8 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.2 MB 355.6 kB/s eta 0:00:21
   ------- -------------------------------- 1.8/9.2 MB 361.3 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 365.2 kB/s eta 0:00:21
   -------- ------------------------------- 1.9/9.2 MB 340.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 337.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 336.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 336.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 336.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 336.8 kB/s eta 0:00:22
   -------- ------------------------------- 1.9/9.2 MB 329.5 kB/s eta 0:00:23
   -------- ------------------------------- 1.9/9.2 MB 329.4 kB/s eta 0:00:23
   -------- ------------------------------- 1.9/9.2 MB 326.8 kB/s eta 0:00:23
   -------- ------------------------------- 1.9/9.2 MB 326.8 kB/s eta 0:00:23
   -------- ------------------------------- 1.9/9.2 MB 326.8 kB/s eta 0:00:23
   -------- ------------------------------- 1.9/9.2 MB 326.8 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 323.5 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 323.5 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 323.5 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 320.3 kB/s eta 0:00:23
   -------- ------------------------------- 2.0/9.2 MB 300.2 kB/s eta 0:00:24
   -------- ------------------------------- 2.0/9.2 MB 300.5 kB/s eta 0:00:24
   -------- ------------------------------- 2.1/9.2 MB 300.7 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 300.2 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 301.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 301.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 299.2 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 300.8 kB/s eta 0:00:24
   --------- ------------------------------ 2.1/9.2 MB 300.2 kB/s eta 0:00:24
   --------- ------------------------------ 2.2/9.2 MB 301.1 kB/s eta 0:00:24
   --------- ------------------------------ 2.2/9.2 MB 302.9 kB/s eta 0:00:24
   --------- ------------------------------ 2.2/9.2 MB 305.2 kB/s eta 0:00:23
   --------- ------------------------------ 2.3/9.2 MB 309.5 kB/s eta 0:00:23
   --------- ------------------------------ 2.3/9.2 MB 309.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.3/9.2 MB 307.8 kB/s eta 0:00:23
   ---------- ----------------------------- 2.3/9.2 MB 306.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.3/9.2 MB 306.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.3/9.2 MB 305.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.4/9.2 MB 307.6 kB/s eta 0:00:23
   ---------- ----------------------------- 2.4/9.2 MB 309.7 kB/s eta 0:00:22
   ---------- ----------------------------- 2.4/9.2 MB 308.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.4/9.2 MB 308.5 kB/s eta 0:00:23
   ---------- ----------------------------- 2.4/9.2 MB 306.8 kB/s eta 0:00:23
   ---------- ----------------------------- 2.4/9.2 MB 308.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.4/9.2 MB 308.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.4/9.2 MB 308.3 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.2 MB 306.0 kB/s eta 0:00:22
   ---------- ----------------------------- 2.5/9.2 MB 303.7 kB/s eta 0:00:23
   ---------- ----------------------------- 2.5/9.2 MB 303.7 kB/s eta 0:00:23
   ---------- ----------------------------- 2.5/9.2 MB 302.8 kB/s eta 0:00:23
   ---------- ----------------------------- 2.5/9.2 MB 302.9 kB/s eta 0:00:23
   ----------- ---------------------------- 2.5/9.2 MB 303.6 kB/s eta 0:00:22
   ----------- ---------------------------- 2.5/9.2 MB 303.6 kB/s eta 0:00:22
   ----------- ---------------------------- 2.6/9.2 MB 305.8 kB/s eta 0:00:22
   ----------- ---------------------------- 2.6/9.2 MB 305.8 kB/s eta 0:00:22
   ----------- ---------------------------- 2.6/9.2 MB 309.6 kB/s eta 0:00:22
   ----------- ---------------------------- 2.7/9.2 MB 313.9 kB/s eta 0:00:21
   ----------- ---------------------------- 2.7/9.2 MB 314.6 kB/s eta 0:00:21
   ----------- ---------------------------- 2.7/9.2 MB 314.6 kB/s eta 0:00:21

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
pip install plotly

Defaulting to user installation because normal site-packages is not writeable
Collecting plotly
  Downloading plotly-6.7.0-py3-none-any.whl.metadata (8.6 kB)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\user\appdata\roaming\python\python311\site-packages (from plotly) (2.20.0)
Requirement already satisfied: packaging in c:\users\user\appdata\roaming\python\python311\site-packages (from plotly) (23.2)
Downloading plotly-6.7.0-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB 1.4 MB/s eta 0:00:08
   ---------------------------------------- 0.0/9.9 MB 393.8 kB/s eta 0:00:26
   ---------------------------------------- 0.1/9.9 MB 409.6 kB/s eta 0:00:25
   ---------------------------------------- 0.1/9.9 MB 409.6 kB/s eta 0:00:25
   ---------------------------------------- 0.1/9.9 MB 328.6 kB/s eta 0:00:30
   ---------------------------------------- 0.1/9.9 MB 437.6 kB/s eta 0:00:23
    --------------------------------------- 0.1/9.9 MB 426.7 kB/s eta 0:00:23
    --------------------------------------- 0.2/9.9 MB 418.0 kB/s eta 0:00:24
    --------------------------------------- 0.2/9.9 MB 418.0 kB/s eta 0:00:24
    --------------------------------------- 0.2/9.9 MB 374.9 kB/s eta 0:00:26
    --------------------------------------- 0.2/9.9 MB 389.1 kB/s eta 0:00:25
    --------------------------------------- 0.2/9.9 MB 405.0 kB/s eta 0:00:24
    --------------------------------------- 0.2/9.9 MB 379.9 kB/s eta 0:00:26
    --------------------------------------- 0.2/9.9 MB 379.9 kB/s eta 0:00:26
   - -------------------------------------- 0.3/9.9 MB 349.6 kB/s eta 0:00:28
   - -------------------------------------- 0.3/9.9 MB 368.6 kB/s eta 0:00:27
   - -------------------------------------- 0.3/9.9 MB 385.4 kB/s eta 0:00:25
   - -------------------------------------- 0.3/9.9 MB 385.4 kB/s eta 0:00:25
   - -------------------------------------- 0.3/9.9 MB 374.5 kB/s eta 0:00:26
   - -------------------------------------- 0.4/9.9 MB 395.6 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.9 MB 395.4 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.9 MB 395.4 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.9 MB 395.4 kB/s eta 0:00:25
   - -------------------------------------- 0.4/9.9 MB 359.3 kB/s eta 0:00:27
   - -------------------------------------- 0.4/9.9 MB 359.3 kB/s eta 0:00:27
   - -------------------------------------- 0.4/9.9 MB 353.1 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.9 MB 359.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.9 MB 359.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.9 MB 350.7 kB/s eta 0:00:27
   - -------------------------------------- 0.5/9.9 MB 350.7 kB/s eta 0:00:27
   -- ------------------------------------- 0.5/9.9 MB 355.7 kB/s eta 0:00:27
   -- ------------------------------------- 0.5/9.9 MB 355.7 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.9 MB 350.4 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.9 MB 363.4 kB/s eta 0:00:26
   -- ------------------------------------- 0.6/9.9 MB 355.2 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.9 MB 355.2 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.9 MB 353.9 kB/s eta 0:00:27
   -- ------------------------------------- 0.6/9.9 MB 353.3 kB/s eta 0:00:27
   -- ------------------------------------- 0.7/9.9 MB 369.7 kB/s eta 0:00:25
   -- ------------------------------------- 0.7/9.9 MB 360.0 kB/s eta 0:00:26
   --- ------------------------------------ 0.8/9.9 MB 381.9 kB/s eta 0:00:24
   --- ------------------------------------ 0.8/9.9 MB 406.6 kB/s eta 0:00:23
   --- ------------------------------------ 0.8/9.9 MB 407.2 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 406.1 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 406.1 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 402.7 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 403.4 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 404.0 kB/s eta 0:00:23
   --- ------------------------------------ 0.9/9.9 MB 403.0 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/9.9 MB 398.5 kB/s eta 0:00:23
   --- ------------------------------------ 1.0/9.9 MB 397.4 kB/s eta 0:00:23
   ---- ----------------------------------- 1.0/9.9 MB 398.3 kB/s eta 0:00:23
   ---- ----------------------------------- 1.0/9.9 MB 399.0 kB/s eta 0:00:23
   ---- ----------------------------------- 1.1/9.9 MB 405.7 kB/s eta 0:00:22
   ---- ----------------------------------- 1.1/9.9 MB 420.2 kB/s eta 0:00:21
   ---- ----------------------------------- 1.1/9.9 MB 416.7 kB/s eta 0:00:22
   ---- ----------------------------------- 1.2/9.9 MB 417.0 kB/s eta 0:00:21
   ---- ----------------------------------- 1.2/9.9 MB 423.6 kB/s eta 0:00:21
   ----- ---------------------------------- 1.3/9.9 MB 437.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 444.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 444.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 444.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.3/9.9 MB 436.9 kB/s eta 0:00:20
   ----- ---------------------------------- 1.4/9.9 MB 442.5 kB/s eta 0:00:20
   ----- ---------------------------------- 1.4/9.9 MB 437.0 kB/s eta 0:00:20
   ----- ---------------------------------- 1.4/9.9 MB 447.8 kB/s eta 0:00:19
   ----- ---------------------------------- 1.5/9.9 MB 449.6 kB/s eta 0:00:19
   ------ --------------------------------- 1.5/9.9 MB 457.9 kB/s eta 0:00:19
   ------ --------------------------------- 1.6/9.9 MB 476.9 kB/s eta 0:00:18
   ------ --------------------------------- 1.7/9.9 MB 489.3 kB/s eta 0:00:17
   ------ --------------------------------- 1.7/9.9 MB 500.5 kB/s eta 0:00:17
   ------- -------------------------------- 1.8/9.9 MB 517.3 kB/s eta 0:00:16
   ------- -------------------------------- 1.9/9.9 MB 539.9 kB/s eta 0:00:15
   -------- ------------------------------- 2.0/9.9 MB 563.8 kB/s eta 0:00:14
   -------- ------------------------------- 2.2/9.9 MB 588.0 kB/s eta 0:00:14
   --------- ------------------------------ 2.3/9.9 MB 608.2 kB/s eta 0:00:13
   --------- ------------------------------ 2.4/9.9 MB 630.7 kB/s eta 0:00:12
   --------- ------------------------------ 2.4/9.9 MB 641.9 kB/s eta 0:00:12
   ---------- ----------------------------- 2.6/9.9 MB 668.8 kB/s eta 0:00:11
   ---------- ----------------------------- 2.7/9.9 MB 689.7 kB/s eta 0:00:11
   ---------- ----------------------------- 2.7/9.9 MB 689.7 kB/s eta 0:00:11
   ----------- ---------------------------- 2.8/9.9 MB 707.1 kB/s eta 0:00:11
   ----------- ---------------------------- 2.9/9.9 MB 721.8 kB/s eta 0:00:10
   ----------- ---------------------------- 3.0/9.9 MB 726.0 kB/s eta 0:00:10
   ------------ --------------------------- 3.1/9.9 MB 742.2 kB/s eta 0:00:10
   ------------ --------------------------- 3.2/9.9 MB 758.4 kB/s eta 0:00:09
   ------------- -------------------------- 3.3/9.9 MB 774.4 kB/s eta 0:00:09
   ------------- -------------------------- 3.4/9.9 MB 785.1 kB/s eta 0:00:09
   -------------- ------------------------- 3.5/9.9 MB 805.0 kB/s eta 0:00:08
   -------------- ------------------------- 3.6/9.9 MB 815.2 kB/s eta 0:00:08
   -------------- ------------------------- 3.7/9.9 MB 832.7 kB/s eta 0:00:08
   --------------- ------------------------ 3.8/9.9 MB 846.2 kB/s eta 0:00:08
   --------------- ------------------------ 3.9/9.9 MB 855.6 kB/s eta 0:00:08
   ---------------- ----------------------- 4.0/9.9 MB 876.0 kB/s eta 0:00:07
   ---------------- ----------------------- 4.2/9.9 MB 899.8 kB/s eta 0:00:07
   ----------------- ---------------------- 4.2/9.9 MB 911.4 kB/s eta 0:00:07
   ----------------- ---------------------- 4.3/9.9 MB 916.7 kB/s eta 0:00:07
   ----------------- ---------------------- 4.4/9.9 MB 931.3 kB/s eta 0:00:06
   ------------------ --------------------- 4.5/9.9 MB 935.0 kB/s eta 0:00:06
   ------------------ --------------------- 4.6/9.9 MB 939.9 kB/s eta 0:00:06
   ------------------ --------------------- 4.7/9.9 MB 957.0 kB/s eta 0:00:06
   ------------------- -------------------- 4.8/9.9 MB 967.6 kB/s eta 0:00:06
   ------------------- -------------------- 4.9/9.9 MB 975.9 kB/s eta 0:00:06
   -------------------- ------------------- 5.0/9.9 MB 983.1 kB/s eta 0:00:06
   -------------------- ------------------- 5.1/9.9 MB 1.0 MB/s eta 0:00:05
   --------------------- ------------------ 5.2/9.9 MB 1.0 MB/s eta 0:00:05
   --------------------- ------------------ 5.3/9.9 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 5.5/9.9 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.1 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 5.6/9.9 MB 1.0 MB/s eta 0:00:05
   ---------------------- ----------------- 5.7/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.8/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.9/9.9 MB 1.0 MB/s eta 0:00:05
   ----------------------- ---------------- 5.9/9.9 MB 998.7 kB/s eta 0:00:05
   ----------------------- ---------------- 5.9/9.9 MB 996.9 kB/s eta 0:00:04
   ------------------------ --------------- 5.9/9.9 MB 990.8 kB/s eta 0:00:04
   ------------------------ --------------- 6.0/9.9 MB 995.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 994.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 994.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 994.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 994.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 994.0 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 962.7 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 954.1 kB/s eta 0:00:04
   ------------------------ --------------- 6.1/9.9 MB 948.7 kB/s eta 0:00:05
   ------------------------ --------------- 6.1/9.9 MB 948.7 kB/s eta 0:00:05
   ------------------------ --------------- 6.1/9.9 MB 938.3 kB/s eta 0:00:05
   ------------------------ --------------- 6.2/9.9 MB 936.3 kB/s eta 0:00:04
   ------------------------ --------------- 6.2/9.9 MB 934.3 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.0 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.2/9.9 MB 933.1 kB/s eta 0:00:04
   ------------------------- -------------- 6.3/9.9 MB 896.3 kB/s eta 0:00:05
   ------------------------- -------------- 6.3/9.9 MB 897.6 kB/s eta 0:00:04
   ------------------------- -------------- 6.4/9.9 MB 896.5 kB/s eta 0:00:04
   ------------------------- -------------- 6.4/9.9 MB 894.9 kB/s eta 0:00:04
   ------------------------- -------------- 6.4/9.9 MB 893.8 kB/s eta 0:00:04
   ------------------------- -------------- 6.4/9.9 MB 889.5 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 882.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 882.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 882.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 882.7 kB/s eta 0:00:04
   -------------------------- ------------- 6.5/9.9 MB 867.5 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 870.2 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 871.1 kB/s eta 0:00:04
   -------------------------- ------------- 6.6/9.9 MB 866.2 kB/s eta 0:00:04
   -------------------------- ------------- 6.7/9.9 MB 867.6 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 867.7 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 866.8 kB/s eta 0:00:04
   --------------------------- ------------ 6.7/9.9 MB 857.8 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 860.4 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 856.1 kB/s eta 0:00:04
   --------------------------- ------------ 6.8/9.9 MB 855.9 kB/s eta 0:00:04
   --------------------------- ------------ 6.9/9.9 MB 856.0 kB/s eta 0:00:04
   --------------------------- ------------ 6.9/9.9 MB 856.1 kB/s eta 0:00:04
   ---------------------------- ----------- 7.0/9.9 MB 863.0 kB/s eta 0:00:04
   ---------------------------- ----------- 7.1/9.9 MB 869.6 kB/s eta 0:00:04
   ----------------------------- ---------- 7.2/9.9 MB 877.2 kB/s eta 0:00:04
   ----------------------------- ---------- 7.3/9.9 MB 881.3 kB/s eta 0:00:03
   ----------------------------- ---------- 7.4/9.9 MB 890.7 kB/s eta 0:00:03
   ------------------------------ --------- 7.5/9.9 MB 897.5 kB/s eta 0:00:03
   ------------------------------ --------- 7.6/9.9 MB 903.9 kB/s eta 0:00:03
   ------------------------------- -------- 7.7/9.9 MB 909.4 kB/s eta 0:00:03
   ------------------------------- -------- 7.8/9.9 MB 911.6 kB/s eta 0:00:03
   -------------------------------- ------- 8.0/9.9 MB 924.7 kB/s eta 0:00:03
   -------------------------------- ------- 8.0/9.9 MB 926.8 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 929.3 kB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 897.7 kB/s eta 0:00:03
   -------------------------------- ------- 8.1/9.9 MB 895.0 kB/s eta 0:00:02
   --------------------------------- ------ 8.3/9.9 MB 903.4 kB/s eta 0:00:02
   --------------------------------- ------ 8.3/9.9 MB 907.0 kB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 907.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 908.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 908.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 900.9 kB/s eta 0:00:02
   ---------------------------------- ----- 8.4/9.9 MB 897.5 kB/s eta 0:00:02
   ---------------------------------- ----- 8.5/9.9 MB 897.4 kB/s eta 0:00:02
   ---------------------------------- ----- 8.5/9.9 MB 896.2 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 898.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 898.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 898.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 898.6 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 880.1 kB/s eta 0:00:02
   ---------------------------------- ----- 8.6/9.9 MB 879.0 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 878.7 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 878.0 kB/s eta 0:00:02
   ----------------------------------- ---- 8.7/9.9 MB 876.2 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 876.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 874.2 kB/s eta 0:00:02
   ----------------------------------- ---- 8.8/9.9 MB 876.2 kB/s eta 0:00:02
   ----------------------------------- ---- 8.9/9.9 MB 872.2 kB/s eta 0:00:02
   ------------------------------------ --- 8.9/9.9 MB 872.2 kB/s eta 0:00:02
   ------------------------------------ --- 9.0/9.9 MB 872.9 kB/s eta 0:00:02
   ------------------------------------ --- 9.0/9.9 MB 871.9 kB/s eta 0:00:02
   ------------------------------------ --- 9.1/9.9 MB 874.8 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 878.4 kB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 881.4 kB/s eta 0:00:01
   ------------------------------------- -- 9.4/9.9 MB 890.4 kB/s eta 0:00:01
   -------------------------------------- - 9.5/9.9 MB 901.0 kB/s eta 0:00:01
   ---------------------------------------  9.7/9.9 MB 912.5 kB/s eta 0:00:01
   ---------------------------------------  9.8/9.9 MB 917.7 kB/s eta 0:00:01
   ---------------------------------------  9.9/9.9 MB 924.6 kB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 919.8 kB/s eta 0:00:00
Installing collected packages: plotly
Successfully installed plotly-6.7.0
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip